### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'cancelToken')

### ISSUE THREAD

**Issue by lovysunny7** [shoesbox/shoesbox-fe#26]
1. 오류 발생
![image](https://user-images.githubusercontent.com/109063966/187935453-df62121f-8724-494d-a5b1-c091ea9bb090.png)

> TypeError: Cannot read properties of undefined (reading 'cancelToken')
    at throwIfCancellationRequested (dispatchRequest.js:13:1)
    at dispatchRequest (dispatchRequest.js:29:1)
    at async Object.getJsonAll (api.jsx:73:1)

2. 해결 
검색해도 잘 안나오길래 헤매다가 오류를 발견하게 되었다.
찾아도 안나오길래 코드를 다시 봤더니, axios의 intercepter 부근에  config를 리턴 시켜줬어야 했는데, 
authorization 부근 주석 처리 하다가 return 값까지 없애서 발생 한 것이였다.
지울 때, 다시 한 번 생각하자

**Comment by caffesale** [comment]
Branch [issue-26](https://github.com/shoesbox/shoesbox-fe/tree/issue-26) created!

**Comment by alsgp0877** [comment]
감사합니다. 해결 하였어요
