### ISSUE TITLE
A non-serializable value was detected in an action, in the path: `payload.config.adapter`

### ISSUE THREAD

**Issue by lovysunny7** [shoesbox/shoesbox-fe#27]
1. 오류 발생
![image](https://user-images.githubusercontent.com/109063966/187948587-36928f55-1d8e-4e13-afaf-cfd91429c219.png)
> A non-serializable value was detected in an action, in the path: `payload.config.adapter`. Value: ƒ xhrAdapter(config) {
  return new Promise(function dispatchXhrRequest(resolve, reject) {
    var requestData = config.data;
    var requestHeaders = config.headers;
    var responseType = config.resp… 

2. 해결
thunk 에서 return 값을 돌려줄 떼, 한층 더 데이터에 접근해서 리턴 시켜주면 해당 오류는 사라진다.

**Comment by caffesale** [comment]
Branch [issue-27](https://github.com/shoesbox/shoesbox-fe/tree/issue-27) created!
