### ISSUE TITLE
Json-db delete doesn't work, it shows 404 response

### ISSUE THREAD

**Issue by lovysunny7** [shoesbox/shoesbox-fe#31]
1. Using the same path, I got different responses
1-1)  post
![image](https://user-images.githubusercontent.com/109063966/188045636-570d1346-a140-4911-b61a-c940cf8f2655.png)
1-2) delete
![image](https://user-images.githubusercontent.com/109063966/188045699-2e1209ae-e79d-4c41-a95f-de9a5796bef5.png)

2.
https://github.com/typicode/json-server/issues/802#issue-332607242

3.
결국 미해결

**Comment by caffesale** [comment]
Branch [issue-31](https://github.com/shoesbox/shoesbox-fe/tree/issue-31) created!
