### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by lovysunny7** [shoesbox/shoesbox-fe#38]
1. 오류 발생
![image](https://user-images.githubusercontent.com/109063966/188244718-1a1b659a-9758-4440-8f6d-98d7c7c36c8d.png)
> Uncaught TypeError: Cannot read properties of undefined (reading 'map')

2. 해결
렌더링할 자료 값 앞에, &&로 조건문을 추가해준다.
`
 previewImages.map((image, idx)=>{
            <Image key={idx} src={image} />
          })
`
`
 previewImages && previewImages.map((image, idx)=>{
            <Image key={idx} src={image} />
          })
`

**Comment by caffesale** [comment]
Branch [issue-38](https://github.com/shoesbox/shoesbox-fe/tree/issue-38) created!
