### ISSUE TITLE
파일 렌더링이 제대로 되지 않은 문제

### ISSUE THREAD

**Issue by lovysunny7** [shoesbox/shoesbox-fe#43]
1. 문제
파일리스트에서 제대로 삭제되는 현상이 발생되지 않은 것이다.
파일도 제대로 읽는데, 왜 그런 현상이 발생하는 지 알 수 없는 상태였다.
![Shoes Box ⁝⁝ Our Moments (1)](https://user-images.githubusercontent.com/109063966/188339062-6ca0da59-7b08-4036-bb31-5b15d140e070.gif)

2. 해결
해결은 의외로 간단했다.
setState에 저장된 값으로 input ref에 연결하여 발생된 문제로, 
업데이트 된 값을 바로 input ref 값을 건드려줘서 해결하였다.
`   setFiles(dataTranster.files);
    imageRef.current.files = files;`
`    imageRef.current.files = dataTranster.files;
`
![Shoes Box ⁝⁝ Our Moments (2)](https://user-images.githubusercontent.com/109063966/188339354-d7ff9d05-04a9-4a80-88c6-d0e5f4a45dfc.gif)

**Comment by caffesale** [comment]
Branch [issue-43](https://github.com/shoesbox/shoesbox-fe/tree/issue-43) created!
