### ISSUE TITLE
axios로 통신이 되는데, console.log에 보이지 않는 현상

### ISSUE THREAD

**Issue by lovysunny7** [shoesbox/shoesbox-fe#45]
1. 문제발생
![image](https://user-images.githubusercontent.com/109063966/188467601-e553275e-4500-42a7-9470-07b5bee74bba.png)
이렇게 통신이 찍히는데, thunk에선 console.log에 나타나지 않는 현상이 발생한 것이다.
다른 팀원과 원인을 찾아봤는데, thunk 새로 axios를 불러들이면 console에 찍히면서 통신 response 값에 접근할 수 가 있었다.
axois를 한 눈에 보기 위해서 관리하는 파일에 문제가 있는 것 같아, 하나씩 실험해 보는 수 밖에 없다는 결론을 내리고, 한 개씩 찾아보게 되었다.

2. 해결
axios를 create하고, interceptors 부분에서 문제가 발생한 것은 아니였다.
하.하.하 정말 사소한 문제 였다 <- 그렇지만 이것 때문에 몇 시간을 고생했는지 모르겠다.
아래와 같이, api 호출을 하게되는데, 이 부분이 무언가 잘못된 것 인지 그대로 아웃라인 파일 받아서 작성해서 아무생각없이 형식 보고 코드를 작성해서 원인을 알 수가 없었다. ~~하하하하하하하하핳.~~
바로 쓸게 아니라면 {} 를 붙이면 안되는 것이였다.
결국 {} 이게 있어서, 시간이 녹아들었다고 한다. {} 제거 하고 나서 데이터에 접근할 수 가 있었다.
`showDetail : (postId) => { api.get(`/posts/${postId}`)} `
>>>>
`showDetail : (postId) => api.get(`/posts/${postId}`)`

**Comment by caffesale** [comment]
Branch [issue-45](https://github.com/shoesbox/shoesbox-fe/tree/issue-45) created!
