### ISSUE TITLE
전체 페이지 기능 디버깅 및 CSS 보완

### ISSUE THREAD

**Issue by hyexjun** [shoesbox/shoesbox-fe#64]
- [x] 마이페이지 프로필 제거(초기화) api 추가
- [x] 댓글에 댓글 작성자 프로필 적용하기
- [x] 댓글 수정창 배치 css 수정

**Comment by caffesale** [comment]
Branch [issue-64](https://github.com/shoesbox/shoesbox-fe/tree/issue-64) created!
